server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/test
    username: postgres
    password: 123456789!

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        function_contributor: com.jpa.starter.infrastructure.contribute.PostgreSQLFunctionContributor

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    org.hibernate.SQL: debug
    org.hibernate.type: trace